version: '3'

services:
  redis:
    image: 'redis:4.0.11-alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  app:
    build: .
    depends_on:
      - 'redis'
    command: npm run dev
    env_file:
      - '.env'
    volumes:
      - '.:/app'

volumes:
  redis: {}
